/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

/**
 *
 * @author Desarrollo01
 */
public class LoginUser extends javax.swing.JFrame {

    /**
     * Creates new form LoginUser
     */
    public LoginUser() {
        initComponents();
        screen();
        iniciar();
    }
    
    public void screen(){
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("../imagenes/logo_fge_64.png")).getImage());
    }
    
    public void iniciar(){
        jButtonX.setBorder(null);
        jButtonX.setContentAreaFilled(false);
        
        jLabelEscudo200.setHorizontalAlignment(SwingConstants.CENTER);
        jLabelEscudo200.setVerticalAlignment(SwingConstants.CENTER);
        
        jLabelBienvenidoTriton.setHorizontalAlignment(SwingConstants.CENTER);
        jLabelBienvenidoTriton.setVerticalAlignment(SwingConstants.CENTER);
        
        jLabelSistemaPersonal.setHorizontalAlignment(SwingConstants.CENTER);
        jLabelSistemaPersonal.setVerticalAlignment(SwingConstants.CENTER);
        
        jLabelCopyright.setHorizontalAlignment(SwingConstants.CENTER);
        jLabelCopyright.setVerticalAlignment(SwingConstants.CENTER);
        
        jLabelUserIco.setHorizontalAlignment(SwingConstants.CENTER);
        jLabelUserIco.setVerticalAlignment(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_principal = new javax.swing.JPanel();
        jPanelIzquierda = new javax.swing.JPanel();
        jLabelEscudo200 = new javax.swing.JLabel();
        jLabelBienvenidoTriton = new javax.swing.JLabel();
        jLabelSistemaPersonal = new javax.swing.JLabel();
        jLabelCopyright = new javax.swing.JLabel();
        jLabelLinea1 = new javax.swing.JLabel();
        jButtonX = new javax.swing.JButton();
        jLabelUserIco = new javax.swing.JLabel();
        jButtonAcceder = new javax.swing.JButton();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldPassword = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(770, 490));
        setMinimumSize(new java.awt.Dimension(770, 490));
        setName("frame_login"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jPanel_principal.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_principal.setForeground(new java.awt.Color(33, 33, 33));
        jPanel_principal.setToolTipText("");
        jPanel_principal.setAlignmentX(0.0F);
        jPanel_principal.setAlignmentY(0.0F);
        jPanel_principal.setMaximumSize(new java.awt.Dimension(770, 490));
        jPanel_principal.setMinimumSize(new java.awt.Dimension(770, 490));
        jPanel_principal.setName(""); // NOI18N
        jPanel_principal.setPreferredSize(new java.awt.Dimension(770, 490));
        jPanel_principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelIzquierda.setBackground(new java.awt.Color(38, 38, 38));
        jPanelIzquierda.setAlignmentX(0.0F);
        jPanelIzquierda.setAlignmentY(0.0F);
        jPanelIzquierda.setMaximumSize(new java.awt.Dimension(385, 490));
        jPanelIzquierda.setMinimumSize(new java.awt.Dimension(385, 490));
        jPanelIzquierda.setPreferredSize(new java.awt.Dimension(385, 490));
        jPanelIzquierda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEscudo200.setBackground(new java.awt.Color(214, 214, 214));
        jLabelEscudo200.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEscudo200.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_fge_200.png"))); // NOI18N
        jLabelEscudo200.setToolTipText("");
        jPanelIzquierda.add(jLabelEscudo200, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 82, 373, -1));

        jLabelBienvenidoTriton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelBienvenidoTriton.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBienvenidoTriton.setText("Bienvenido a TRITON");
        jLabelBienvenidoTriton.setToolTipText("");
        jPanelIzquierda.add(jLabelBienvenidoTriton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 314, 373, -1));

        jLabelSistemaPersonal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelSistemaPersonal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSistemaPersonal.setText("Sistema de Personal");
        jLabelSistemaPersonal.setToolTipText("");
        jPanelIzquierda.add(jLabelSistemaPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 356, 373, -1));

        jLabelCopyright.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabelCopyright.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCopyright.setText("Copyright ® Fiscalía General del Estado");
        jLabelCopyright.setToolTipText("");
        jPanelIzquierda.add(jLabelCopyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 455, 373, -1));

        jPanel_principal.add(jPanelIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelLinea1.setBackground(new java.awt.Color(214, 214, 214));
        jLabelLinea1.setForeground(new java.awt.Color(38, 38, 38));
        jLabelLinea1.setText("_____________________________________________________");
        jLabelLinea1.setToolTipText("");
        jPanel_principal.add(jLabelLinea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 105, -1, 20));

        jButtonX.setBackground(new java.awt.Color(255, 255, 255));
        jButtonX.setForeground(new java.awt.Color(255, 255, 255));
        jButtonX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        jButtonX.setToolTipText("");
        jButtonX.setBorder(null);
        jButtonX.setBorderPainted(false);
        jButtonX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonX.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonX.setMaximumSize(new java.awt.Dimension(30, 30));
        jButtonX.setMinimumSize(new java.awt.Dimension(30, 30));
        jButtonX.setName("jButtonX"); // NOI18N
        jButtonX.setOpaque(false);
        jButtonX.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonX.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel_dark.png"))); // NOI18N
        jButtonX.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel_over.png"))); // NOI18N
        jButtonX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonXMouseClicked(evt);
            }
        });
        jPanel_principal.add(jButtonX, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 6, -1, -1));

        jLabelUserIco.setBackground(new java.awt.Color(214, 214, 214));
        jLabelUserIco.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelUserIco.setForeground(new java.awt.Color(204, 204, 204));
        jLabelUserIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        jLabelUserIco.setText("   Acceso al Sistema");
        jLabelUserIco.setToolTipText("");
        jPanel_principal.add(jLabelUserIco, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 370, -1));

        jButtonAcceder.setBackground(new java.awt.Color(26, 123, 185));
        jButtonAcceder.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonAcceder.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAcceder.setText("Acceder");
        jButtonAcceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_principal.add(jButtonAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 392, 300, 40));

        jTextFieldEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldEmail.setToolTipText("");
        jTextFieldEmail.setBorder(null);
        jTextFieldEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_principal.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 300, 40));

        jTextFieldPassword.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldPassword.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldPassword.setToolTipText("");
        jTextFieldPassword.setBorder(null);
        jTextFieldPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_principal.add(jTextFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 300, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonXMouseClicked
        // TODO add your handling code here:
        // System.exit(LoginUser.EXIT_ON_CLOSE);
        // this.setVisible(false);        
        System.exit(0);
    }//GEN-LAST:event_jButtonXMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcceder;
    private javax.swing.JButton jButtonX;
    private javax.swing.JLabel jLabelBienvenidoTriton;
    private javax.swing.JLabel jLabelCopyright;
    private javax.swing.JLabel jLabelEscudo200;
    private javax.swing.JLabel jLabelLinea1;
    private javax.swing.JLabel jLabelSistemaPersonal;
    private javax.swing.JLabel jLabelUserIco;
    private javax.swing.JPanel jPanelIzquierda;
    private javax.swing.JPanel jPanel_principal;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldPassword;
    // End of variables declaration//GEN-END:variables
}
